function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t229__list_item a[href='"+url+"']").addClass("t-active");$(".t229__list_item a[href='"+url+"/']").addClass("t-active");$(".t229__list_item a[href='"+pathname+"']").addClass("t-active");$(".t229__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t229__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t229__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t229_checkAnchorLinks(recid){if($(window).width()>=960){var t229_navLinks=$("#rec"+recid+" .t229__list_item a:not(.tooltipstered)[href*='#']");if(t229_navLinks.length>0){t229_catchScroll(t229_navLinks)}}}
function t229_catchScroll(t229_navLinks){var t229_clickedSectionId=null,t229_sections=new Array(),t229_sectionIdTonavigationLink=[],t229_interval=100,t229_lastCall,t229_timeoutId;t229_navLinks=$(t229_navLinks.get().reverse());t229_navLinks.each(function(){var t229_cursection=t229_getSectionByHref($(this));if(typeof t229_cursection.attr("id")!="undefined"){t229_sections.push(t229_cursection)}
t229_sectionIdTonavigationLink[t229_cursection.attr("id")]=$(this)});t229_updateSectionsOffsets(t229_sections);t229_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t229_updateSectionsOffsets(t229_sections)},200));$('.t229').bind('displayChanged',function(){t229_updateSectionsOffsets(t229_sections)});setInterval(function(){t229_updateSectionsOffsets(t229_sections)},5000);t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId);t229_navLinks.click(function(){var t229_clickedSection=t229_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t229_clickedSection.attr("id")!="undefined"){t229_navLinks.removeClass('t-active');$(this).addClass('t-active');t229_clickedSectionId=t229_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t229_now=new Date().getTime();if(t229_lastCall&&t229_now<(t229_lastCall+t229_interval)){clearTimeout(t229_timeoutId);t229_timeoutId=setTimeout(function(){t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)},t229_interval-(t229_now-t229_lastCall))}else{t229_lastCall=t229_now;t229_clickedSectionId=t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId)}})}
function t229_updateSectionsOffsets(sections){$(sections).each(function(){var t229_curSection=$(this);t229_curSection.attr("data-offset-top",t229_curSection.offset().top)})}
function t229_getSectionByHref(curlink){var t229_curLinkValue=curlink.attr("href").replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t229_curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t229_curLinkValue+"']")}}
function t229_highlightNavLinks(t229_navLinks,t229_sections,t229_sectionIdTonavigationLink,t229_clickedSectionId){var t229_scrollPosition=$(window).scrollTop(),t229_valueToReturn=t229_clickedSectionId;if(t229_sections.length!=0&&t229_clickedSectionId==null&&t229_sections[t229_sections.length-1].attr("data-offset-top")>(t229_scrollPosition+300)){t229_navLinks.removeClass('t-active');return null}
$(t229_sections).each(function(e){var t229_curSection=$(this),t229_sectionTop=t229_curSection.attr("data-offset-top"),t229_id=t229_curSection.attr('id'),t229_navLink=t229_sectionIdTonavigationLink[t229_id];if(((t229_scrollPosition+300)>=t229_sectionTop)||(t229_sections[0].attr("id")==t229_id&&t229_scrollPosition>=$(document).height()-$(window).height())){if(t229_clickedSectionId==null&&!t229_navLink.hasClass('t-active')){t229_navLinks.removeClass('t-active');t229_navLink.addClass('t-active');t229_valueToReturn=null}else{if(t229_clickedSectionId!=null&&t229_id==t229_clickedSectionId){t229_valueToReturn=null}}
return!1}});return t229_valueToReturn}
function t229_setPath(pageid){}
function t229_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t229").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t229").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t229_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$("#rec"+recid+" .t229").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t229_changeBgOpacityMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t229").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll)}else{el.css("background-color",bgcolor)}})}}
function t527_setHeight(recid){var t527__el=$("#rec"+recid),t527__image=t527__el.find(".t527__bgimg:first"),t527__width=t527__image.attr("data-image-width"),t527__height=t527__image.attr("data-image-height"),t527__ratio=t527__height/t527__width,t527__padding=t527__ratio*100;$("#rec"+recid+" .t527__bgimg").css("padding-bottom",t527__padding+"%")}
function t690_onSuccess(t690_form){var t690_inputsWrapper=t690_form.find('.t-form__inputsbox');var t690_inputsHeight=t690_inputsWrapper.height();var t690_inputsOffset=t690_inputsWrapper.offset().top;var t690_inputsBottom=t690_inputsHeight+t690_inputsOffset;var t690_targetOffset=t690_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t690_target=t690_targetOffset-200}else{var t690_target=t690_targetOffset-100}
if(t690_targetOffset>$(window).scrollTop()||($(document).height()-t690_inputsBottom)<($(window).height()-100)){t690_inputsWrapper.addClass('t690__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t690_target},400);setTimeout(function(){t690_inputsWrapper.addClass('t690__inputsbox_hidden')},400)}
var successurl=t690_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);el.find(".t-cover__container").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t706_onSuccessCallback(t706_form){$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t776__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t776_initPopup(recid);t776__hoverZoom_init(recid);t776__updateLazyLoad(recid);t776__alignButtons_init(recid);if(typeof t_store_addProductQuantityEvents!=='undefined'){t776_initProductQuantity(recid)}
$('body').trigger('twishlist_addbtn')},500)}
function t776_initProductQuantity(recid){var el=$('#rec'+recid);var productList=el.find(".t776__col, .t776__product-full");productList.each(function(i,product){t_store_addProductQuantityEvents($(product))})}
function t776__showMore(recid){var el=$('#rec'+recid).find(".t776");var showmore=el.find('.t776__showmore');var cards_count=parseInt(el.attr('data-show-count'),10);if(cards_count>0){if(showmore.text()===''){showmore.find('td').text(t776__dict('loadmore'))}
showmore.show();el.find('.t776__col').hide();var cards_size=el.find('.t776__col').size();var x=cards_count;var y=cards_count;t776__showSeparator(el,x);el.find('.t776__col:lt('+x+')').show();showmore.click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t776__col:lt('+x+')').show();if(x==cards_size){showmore.hide()}
t776__showSeparator(el,x);if($('#rec'+recid).find('[data-buttons-v-align]')[0]){t776__alignButtons(recid)}
if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t776__showSeparator(el,x){el.find('.t776__separator_number').addClass('t776__separator_hide');el.find('.t776__separator_hide').each(function(){if($(this).attr('data-product-separator-number')<=x){$(this).removeClass('t776__separator_hide')}})}
function t776__dict(msg){var dict=[];dict.loadmore={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var lang=window.browserLang;if(typeof dict[msg]!=='undefined'){if(typeof dict[msg][lang]!=='undefined'&&dict[msg][lang]!=''){return dict[msg][lang]}else{return dict[msg].EN}}
return 'Text not found "'+msg+'"'}
function t776__alignButtons_init(recid){var el=$('#rec'+recid);if(el.find('[data-buttons-v-align]')[0]){try{t776__alignButtons(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t776__alignButtons(recid)}));el.find('.t776').bind('displayChanged',function(){t776__alignButtons(recid)});if($isMobile){$(window).on('orientationchange',function(){t776__alignButtons(recid)})}}catch(e){console.log('buttons-v-align error: '+e.message)}}}
function t776__alignButtons(recid){var rec=$('#rec'+recid);var wrappers=rec.find('.t776__textwrapper');var maxHeight=0;var itemsInRow=rec.find('.t-container').attr('data-blocks-per-row')*1;var mobileView=$(window).width()<=480;var tableView=$(window).width()<=960&&$(window).width()>480;var mobileOneRow=$(window).width()<=960&&rec.find('.t776__container_mobile-flex')[0]?true:!1;var mobileTwoItemsInRow=$(window).width()<=480&&rec.find('.t776 .mobile-two-columns')[0]?true:!1;if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var i=1;var wrappersInRow=[];$.each(wrappers,function(key,element){element.style.height='auto';if(itemsInRow===1){element.style.height='auto'}else{wrappersInRow.push(element);if(element.offsetHeight>maxHeight){maxHeight=element.offsetHeight}
$.each(wrappersInRow,function(key,wrapper){wrapper.style.height=maxHeight+'px'});if(i===itemsInRow){i=0;maxHeight=0;wrappersInRow=[]}
i++}})}
function t776__hoverZoom_init(recid){if(isMobile){return}
var rec=$('#rec'+recid);try{if(rec.find('[data-hover-zoom]')[0]){if(!jQuery.cachedZoomScript){jQuery.cachedZoomScript=function(url){var options={dataType:'script',cache:!0,url:url};return jQuery.ajax(options)}}
$.cachedZoomScript('https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js').done(function(script,textStatus){if(textStatus=='success'){setTimeout(function(){t_hoverZoom_init(recid)},500)}else{console.log('Upload script error: '+textStatus)}})}}catch(e){console.log('Zoom image init error: '+e.message)}}
function t776__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t776__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"){scrollContainer.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t776_initPopup(recid){var rec=$('#rec'+recid);rec.find('[href^="#prodpopup"]').each(function(e){var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');$(".r").find('a[href$="#!/tproduct/'+recid+'-'+lid_prod+'"]').click(function(e){if(rec.find('[data-product-lid='+lid_prod+']').length){rec.find('[data-product-lid='+lid_prod+'] [href^="#prodpopup"]').triggerHandler('click')}})});rec.find('[href^="#prodpopup"]').one("click",function(e){e.preventDefault();var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t776__product-'+lid_prod+'')})});rec.find('[href^="#prodpopup"]').click(function(e){e.preventDefault();if($(e.target).hasClass('t1002__addBtn')||$(e.target).parents().hasClass('t1002__addBtn')){return}
t776_showPopup(recid);var el_popup=rec.find('.t-popup');var el_prod=$(this).closest('.js-product');var lid_prod=el_prod.attr('data-product-lid');el_popup.find('.js-product').css('display','none');var el_fullprod=el_popup.find('.js-product[data-product-lid="'+lid_prod+'"]');el_fullprod.css('display','block');var analitics=el_popup.attr('data-track-popup');if(analitics>''){var virtTitle=el_fullprod.find('.js-product-name').text();if(!virtTitle){virtTitle='prod'+lid_prod}
Tilda.sendEventToStatistics(analitics,virtTitle)}
var curUrl=window.location.href;if(curUrl.indexOf('#!/tproduct/')<0&&curUrl.indexOf('%23!/tproduct/')<0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+lid_prod)}}
t776_updateSlider(recid+' #t776__product-'+lid_prod+'');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});if($('#record'+recid).length==0){t776_checkUrl(recid)}
t776_copyTypography(recid)}
function t776_checkUrl(recid){var curUrl=window.location.href;var tprodIndex=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&tprodIndex<0){tprodIndex=curUrl.indexOf('%23!/tproduct/')}
if(tprodIndex>=0){var curUrl=curUrl.substring(tprodIndex,curUrl.length);var curProdLid=curUrl.substring(curUrl.indexOf('-')+1,curUrl.length);var rec=$('#rec'+recid);if(curUrl.indexOf(recid)>=0&&rec.find('[data-product-lid='+curProdLid+']').length){rec.find('[data-product-lid='+curProdLid+'] [href^="#prodpopup"]').triggerHandler('click')}}}
function t776_updateSlider(recid){var el=$('#rec'+recid);t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t776_showPopup(recid){var el=$('#rec'+recid);var popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},50);$('body').addClass('t-body_popupshowed');$('body').trigger('twishlist_addbtn');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t776_closePopup()}});el.find('.t-popup__close, .t776__close-text').click(function(e){t776_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t776_closePopup()}});if(window.isSafari){setTimeout(function(){el.find('.t-popup').scrollTop(1)})}}
function t776_closePopup(){$('body').removeClass('t-body_popupshowed');$('body').trigger('twishlist_addbtn');$('.t-popup').removeClass('t-popup_show');var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tproduct/')}
curUrl=curUrl.substring(0,indexToRemove);setTimeout(function(){$(".t-popup").scrollTop(0);$('.t-popup').not('.t-popup_show').css('display','none');if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}},300)}
function t776_removeSizeStyles(styleStr){if(typeof styleStr!="undefined"&&(styleStr.indexOf('font-size')>=0||styleStr.indexOf('padding-top')>=0||styleStr.indexOf('padding-bottom')>=0)){var styleStrSplitted=styleStr.split(';');styleStr="";for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')>=0||styleStrSplitted[i].indexOf('padding-top')>=0||styleStrSplitted[i].indexOf('padding-bottom')>=0){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]==""){continue}
styleStr+=styleStrSplitted[i]+";"}}
return styleStr}
function t776_copyTypography(recid){var rec=$('#rec'+recid);var titleStyle=rec.find('.t776__title').attr('style');var descrStyle=rec.find('.t776__descr').attr('style');rec.find('.t-popup .t776__title').attr("style",t776_removeSizeStyles(titleStyle));rec.find('.t-popup .t776__descr, .t-popup .t776__text').attr("style",t776_removeSizeStyles(descrStyle))}